# Generated by Django 3.2.4 on 2021-06-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('xirr', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('exchange', models.CharField(choices=[('TSX', 'Toronto Stock Exchange'), ('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'Nasdaq')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('type', models.CharField(choices=[('DEP', 'Deposit'), ('BUY', 'Buy'), ('SEL', 'Sell'), ('DIV', 'Dividend'), ('INT', 'Interest'), ('WIT', 'Withdrawal'), ('NRT', 'Non resident tax')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('number_of_shares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dividend_per_share', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('original_transaction_row', models.CharField(max_length=200, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.account')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.stock')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('symbol', 'exchange'), name='unique_symbol_exchange'),
        ),
        migrations.AddField(
            model_name='price',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.stock', unique_for_date='date'),
        ),
        migrations.AddField(
            model_name='position',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.account'),
        ),
        migrations.AddField(
            model_name='position',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.stock'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('stock', 'account'), name='unique_stock_account'),
        ),
    ]
