# Generated by Django 3.2.4 on 2021-06-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='xirr_percent',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
