# Generated by Django 3.2.4 on 2021-06-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_position_xirr_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='xirr_percent',
        ),
    ]
